services:

  db:
    image: postgres:16
    container_name: achievement-db

    restart: always

    env_file:
      - .env

    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:

    build: ./backend

    container_name: achievement-backend

    restart: always

    env_file:
      - .env
    expose:
      - "8000"

    depends_on:
      db:
        condition: service_healthy

  frontend:

    build: ./frontend

    container_name: achievement-frontend

    restart: always

    ports:
      - "3000:80"

    depends_on:
      - backend

volumes:

  postgres_data:
