services:

  nginx:
    image: nginx:alpine
    container_name: achievement-nginx

    ports:
      - "80:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      - frontend-add
      - frontend-list

    networks:
      - achievement-network


  frontend-add:
    build:
      context: ./frontend-add

    container_name: achievement-frontend-add

    depends_on:
      - backend

    networks:
      - achievement-network


  frontend-list:
    build:
      context: ./frontend-list

    container_name: achievement-frontend-list

    depends_on:
      - backend

    networks:
      - achievement-network


  backend:
    build:
      context: ./backend

    container_name: achievement-backend

    restart: always

    env_file:
      - .env

    expose:
      - "8000"

    depends_on:
      db:
        condition: service_healthy

    networks:
      - achievement-network


  db:
    image: postgres:16

    container_name: achievement-db

    restart: always

    env_file:
      - .env

    expose:
      - "5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]

      interval: 5s
      timeout: 5s
      retries: 5

    networks:
      - achievement-network


volumes:

  postgres_data:


networks:

  achievement-network:
    driver: bridge
